In [1]:
import numpy as np
import pandas as pd

In [4]:
s = pd.Series([1, 3, 5, 6, 8])
s

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [3]:
# q1 : create a series using tuple, set, dict
# q2 : create a series using numpy array

In [5]:
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
a  = [21,43,65,87,98]
s = pd.Series(a, index = ['a','b','c','d','e'])
s
print(s.size)
print(s.shape)
print(s.ndim)
print(s.dtype)

5
(5,)
1
int64

AttributeError: 'list' object has no attribute 'dtype'

In [25]:
a  = [21,43,65,87,98]
s = pd.Series(a, name = "prachi")
s
s.info()
s.describe()
type(s)

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: prachi
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

pandas.Series

In [33]:
# Dataframe

l = [1,2,3,4,5]
df = pd.DataFrame(l,columns = ['numbers'])
df
print(type(df))
df.size
df.shape

<class 'pandas.DataFrame'>

(5, 1)

In [36]:
# creating dataframe using dict

data = {
    'name' : ['prachi','muskan','priyanka'],
    'course' : ['python','java','c++'],
    }

df = pd.DataFrame(data)
df

       name  course
0    prachi  python
1    muskan    java
2  priyanka     c++

In [41]:
task = {
    'Id' : [1,2,3,4],
    'Dept' : ['IT','HR','IT', 'Ds'],
    'City' : ['Bhopal','Indore','Bhopal','Ujjain'],
    'Salary' : [10000,20000,30000,40000]
}
task
df = pd.DataFrame(task, index= ['a','b', 'c','d'])
df
df.info()
df

<class 'pandas.DataFrame'>
Index: 4 entries, a to d
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      4 non-null      int64
 1   Dept    4 non-null      str
 2   City    4 non-null      str
 3   Salary  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 160.0+ bytes

   Id Dept    City  Salary
a   1   IT  Bhopal   10000
b   2   HR  Indore   20000
c   3   IT  Bhopal   30000
d   4   Ds  Ujjain   40000

In [48]:
task = {
    'Id' : [1,2,3,4],
    'Dept' : ['IT','np.nan','IT', 'Ds'],
    'City' : ['Bhopal','Indore','Bhopal','Ujjain'],
    'Salary' : [10000,np.nan,30000,np.nan]
}
df = pd.DataFrame(task)
df.isna().sum().sum()

np.int64(2)