In [1]:
import pandas as pd

In [2]:
import pandas as pd
df1=pd.DataFrame({
    'ID':[4,5,6],
    'Name':["Aman","Riya","Kiran"]
}
)
df2=pd.DataFrame({
    'ID':[4,5,6],
    'Name':["Neha ","Raj","Simran"]
}
)

In [3]:
pd.concat([df1,df2],axis=0)

   ID    Name
0   4    Aman
1   5    Riya
2   6   Kiran
0   4   Neha
1   5     Raj
2   6  Simran

In [4]:
pd.concat([df1,df2],axis=0, ignore_index=True)

   ID    Name
0   4    Aman
1   5    Riya
2   6   Kiran
3   4   Neha
4   5     Raj
5   6  Simran